version: "3.9"

services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: Inventory
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      

  server:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: Inventory
      DB_PORT: 5432
      PORT: 3000
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  client:
    build: ./frontend/my-react-app
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./frontend/my-react-app:/app
      - /app/node_modules

volumes:
  pgdata: